# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(991, 731)
        Form.setStyleSheet("#Form{\n"
"    \n"
"    background-color: rgb(194, 194, 194);\n"
"}\n"
"#scrollArea\n"
"{\n"
"    border:1px solid black;\n"
"    border-radius: 3px;\n"
"}\n"
"#scrollAreaWidgetContents\n"
"{\n"
"    border:1px solid black;\n"
"    border-radius: 5px;\n"
"}\n"
"#frame_3\n"
"{\n"
"    border-radius: 3px;\n"
"}\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setMaximumSize(QtCore.QSize(250, 16777215))
        self.splitter.setStyleSheet("background-color: rgb(194, 194, 194);")
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.frame_2 = QtWidgets.QFrame(self.splitter)
        self.frame_2.setMinimumSize(QtCore.QSize(250, 50))
        self.frame_2.setMaximumSize(QtCore.QSize(250, 50))
        self.frame_2.setStyleSheet("#frame_2 {\n"
"    border: 1px solid black;\n"
"border-radius: 5px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(-1, 5, -1, 9)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.scrollArea = QtWidgets.QScrollArea(self.splitter)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(300, 16777215))
        self.scrollArea.setStyleSheet("background-color: rgb(133, 133, 133);")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -534, 227, 1200))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setMinimumSize(QtCore.QSize(0, 1200))
        self.frame.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame.setStyleSheet("#frame{background-color: rgb(255, 255, 255);}\n"
"#frame QPushButton {\n"
"    padding-top:10px;\n"
"    padding-bottom:10px;\n"
"    font-size: 20px;\n"
"    height:30px;\n"
"    color: white;\n"
"    background-color: rgb(10, 186, 181);\n"
"    font-family: \"JetBrains Mono\", monospace;\n"
"    font: bold;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(9, 0, -1, 0)
        self.verticalLayout_3.setSpacing(9)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.National = QtWidgets.QPushButton(self.frame)
        self.National.setMinimumSize(QtCore.QSize(0, 0))
        self.National.setObjectName("National")
        self.verticalLayout_3.addWidget(self.National)
        self.Latest = QtWidgets.QPushButton(self.frame)
        self.Latest.setObjectName("Latest")
        self.verticalLayout_3.addWidget(self.Latest)
        self.Litareture = QtWidgets.QPushButton(self.frame)
        self.Litareture.setObjectName("Litareture")
        self.verticalLayout_3.addWidget(self.Litareture)
        self.Political = QtWidgets.QPushButton(self.frame)
        self.Political.setObjectName("Political")
        self.verticalLayout_3.addWidget(self.Political)
        self.Economics = QtWidgets.QPushButton(self.frame)
        self.Economics.setObjectName("Economics")
        self.verticalLayout_3.addWidget(self.Economics)
        self.International = QtWidgets.QPushButton(self.frame)
        self.International.setObjectName("International")
        self.verticalLayout_3.addWidget(self.International)
        self.Country = QtWidgets.QPushButton(self.frame)
        self.Country.setObjectName("Country")
        self.verticalLayout_3.addWidget(self.Country)
        self.Entertainment = QtWidgets.QPushButton(self.frame)
        self.Entertainment.setObjectName("Entertainment")
        self.verticalLayout_3.addWidget(self.Entertainment)
        self.Education = QtWidgets.QPushButton(self.frame)
        self.Education.setObjectName("Education")
        self.verticalLayout_3.addWidget(self.Education)
        self.Jobs = QtWidgets.QPushButton(self.frame)
        self.Jobs.setObjectName("Jobs")
        self.verticalLayout_3.addWidget(self.Jobs)
        self.Technology = QtWidgets.QPushButton(self.frame)
        self.Technology.setObjectName("Technology")
        self.verticalLayout_3.addWidget(self.Technology)
        self.LifeStyle = QtWidgets.QPushButton(self.frame)
        self.LifeStyle.setObjectName("LifeStyle")
        self.verticalLayout_3.addWidget(self.LifeStyle)
        self.Islam = QtWidgets.QPushButton(self.frame)
        self.Islam.setObjectName("Islam")
        self.verticalLayout_3.addWidget(self.Islam)
        self.Various = QtWidgets.QPushButton(self.frame)
        self.Various.setObjectName("Various")
        self.verticalLayout_3.addWidget(self.Various)
        self.Socialmedia = QtWidgets.QPushButton(self.frame)
        self.Socialmedia.setObjectName("Socialmedia")
        self.verticalLayout_3.addWidget(self.Socialmedia)
        self.Interview = QtWidgets.QPushButton(self.frame)
        self.Interview.setObjectName("Interview")
        self.verticalLayout_3.addWidget(self.Interview)
        self.Corporate = QtWidgets.QPushButton(self.frame)
        self.Corporate.setObjectName("Corporate")
        self.verticalLayout_3.addWidget(self.Corporate)
        self.Others = QtWidgets.QPushButton(self.frame)
        self.Others.setObjectName("Others")
        self.verticalLayout_3.addWidget(self.Others)
        self.verticalLayout.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.splitter)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setStyleSheet("background-color: rgb(194, 194, 194);")
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_3 = QtWidgets.QFrame(self.widget)
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Tittle_Load_Label = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Tittle_Load_Label.setFont(font)
        self.Tittle_Load_Label.setStyleSheet("background-color: rgb(218, 218, 218);\n"
"border: 1px solid black;\n"
"border-radius: 3px;")
        self.Tittle_Load_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Tittle_Load_Label.setObjectName("Tittle_Load_Label")
        self.verticalLayout_4.addWidget(self.Tittle_Load_Label)
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_4)
        self.stackedWidget.setEnabled(True)
        font = QtGui.QFont()
        font.setKerning(True)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.ListWidgetPage = QtWidgets.QWidget()
        self.ListWidgetPage.setEnabled(True)
        self.ListWidgetPage.setObjectName("ListWidgetPage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.ListWidgetPage)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.ListWidgetPage)
        self.listWidget.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_2.addWidget(self.listWidget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.ListWidgetPage)
        self.NewsShow = QtWidgets.QWidget()
        self.NewsShow.setObjectName("NewsShow")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.NewsShow)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.textEdit = QtWidgets.QTextEdit(self.NewsShow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("border:1px solid black;")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_6.addWidget(self.textEdit)
        self.imageLabel = QtWidgets.QLabel(self.NewsShow)
        self.imageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.imageLabel.setObjectName("imageLabel")
        self.verticalLayout_6.addWidget(self.imageLabel)
        self.stackedWidget.addWidget(self.NewsShow)
        self.verticalLayout_4.addWidget(self.stackedWidget)
        self.verticalLayout_5.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setStyleSheet("#frame_5 QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                                      stop:0 #f8e9d4, stop:1 #eacda3);\n"
"    padding: 10px 20px;\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #e0c3a0;\n"
"    border-radius: 8px;\n"
"    color: #5a463a;\n"
"    box-shadow: 2px 2px 6px rgba(0, 0, 0, 0.2);\n"
"}\n"
"\n"
"/* Hover Effect */\n"
"#frame_5 QPushButton:hover {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                                      stop:0 #ffe3c8, stop:1 #f7c58e);\n"
"    border: 2px solid #d6b27c;\n"
"    color: #3b2f24;\n"
"    transform: scale(1.03);\n"
"}\n"
"\n"
"/* Pressed Effect */\n"
"#frame_5 QPushButton:pressed {\n"
"    background-color: #e5bb91;\n"
"    border: 2px solid #b8946b;\n"
"}\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.BackButton = QtWidgets.QPushButton(self.frame_5)
        self.BackButton.setObjectName("BackButton")
        self.horizontalLayout_2.addWidget(self.BackButton)
        self.PostButton = QtWidgets.QPushButton(self.frame_5)
        self.PostButton.setObjectName("PostButton")
        self.horizontalLayout_2.addWidget(self.PostButton)
        self.verticalLayout_5.addWidget(self.frame_5)
        self.gridLayout.addWidget(self.frame_3, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "News Section"))
        self.National.setText(_translate("Form", "National"))
        self.Latest.setText(_translate("Form", "Latest"))
        self.Litareture.setText(_translate("Form", "Litareture"))
        self.Political.setText(_translate("Form", "Political"))
        self.Economics.setText(_translate("Form", "Economics"))
        self.International.setText(_translate("Form", "International"))
        self.Country.setText(_translate("Form", "Country"))
        self.Entertainment.setText(_translate("Form", "Entertainment"))
        self.Education.setText(_translate("Form", "Education"))
        self.Jobs.setText(_translate("Form", "Jobs"))
        self.Technology.setText(_translate("Form", "Technology"))
        self.LifeStyle.setText(_translate("Form", "LifeStyle"))
        self.Islam.setText(_translate("Form", "Islam"))
        self.Various.setText(_translate("Form", "Various"))
        self.Socialmedia.setText(_translate("Form", "Socialmedia"))
        self.Interview.setText(_translate("Form", "Interview"))
        self.Corporate.setText(_translate("Form", "Corporate"))
        self.Others.setText(_translate("Form", "Others"))
        self.Tittle_Load_Label.setText(_translate("Form", "News Loader"))
        self.imageLabel.setText(_translate("Form", "TextLabel"))
        self.BackButton.setText(_translate("Form", "Back"))
        self.PostButton.setText(_translate("Form", "Post"))
